"""constants for project"""
HF_API_KEY = "HF_API_KEY"
HF_API_SUMMARY_BASE = "HF_API_SUMMARY_BASE"

OPENAI_API_KEY = "OPENAI_API_KEY"
OPENAI_API_BASE = "OPENAI_API_BASE"
OPENAI_API_VERSION = "OPENAI_API_VERSION"
AZURE = "azure"
DEPLOYMENT_NAME = "DEPLOYMENT_NAME"


GPT_3DOT5_TURBO = "gpt-3.5-turbo"
